Repository codals/greating, pull requests merged in 2023-06, with the labels that each got.

#96 마이페이지 페이지네이션 완료
  src/main/java/com/codals/greating/mypage/controller/MyPageController.java
  src/main/java/com/codals/greating/mypage/dao/MyPageDao.java
  src/main/java/com/codals/greating/mypage/dao/MyPageDaoImpl.java
  src/main/java/com/codals/greating/mypage/dto/MyPageDto.java
  src/main/java/com/codals/greating/mypage/dto/MyPageScrapDto.java
  src/main/java/com/codals/greating/mypage/service/MyPageService.java
  src/main/java/com/codals/greating/mypage/service/MyPageServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/mappers/MyPage.xml
  src/main/webapp/WEB-INF/views/user/mypage-mydiy.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myscrap.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myvote.jsp
  src/main/webapp/resources/css/user/mypage-myscrap.css
  src/main/webapp/resources/css/user/mypage-pagination.css
  src/main/webapp/resources/images/user/exclamationMark.png
Labels: enhancement

#104 식단 미리보기 및 주문 기능 구현
  src/main/java/com/codals/greating/constant/SessionKey.java
  src/main/java/com/codals/greating/diet/controller/DietController.java
  src/main/java/com/codals/greating/diet/controller/DietRestController.java
  src/main/java/com/codals/greating/diet/dao/DailyDietDao.java
  src/main/java/com/codals/greating/diet/dao/DailyDietDaoImpl.java
  src/main/java/com/codals/greating/diet/dao/DietDao.java
  src/main/java/com/codals/greating/diet/dao/DietDaoImpl.java
  src/main/java/com/codals/greating/diet/dao/OrderDao.java
  src/main/java/com/codals/greating/diet/dao/OrderDaoImpl.java
  src/main/java/com/codals/greating/diet/dao/OrderDietDao.java
  src/main/java/com/codals/greating/diet/dao/OrderDietDaoImpl.java
  src/main/java/com/codals/greating/diet/dto/DietDeliveryRequestDto.java
  src/main/java/com/codals/greating/diet/dto/OrderDetailResponseDto.java
  src/main/java/com/codals/greating/diet/dto/OrderDietDto.java
  src/main/java/com/codals/greating/diet/dto/OrderDietRequestDto.java
  src/main/java/com/codals/greating/diet/dto/OrderDietsByDateDto.java
  src/main/java/com/codals/greating/diet/dto/OrderRequestDto.java
  src/main/java/com/codals/greating/diet/dto/OrderResponseDto.java
  src/main/java/com/codals/greating/diet/dto/OrderResultResponseDto.java
  src/main/java/com/codals/greating/diet/dto/PlanResponseDto.java
  src/main/java/com/codals/greating/diet/dto/PreviewDietResponseDto.java
  src/main/java/com/codals/greating/diet/dto/PreviewResponseDto.java
  src/main/java/com/codals/greating/diet/entity/DailyDiet.java
  src/main/java/com/codals/greating/diet/entity/DeliveryStatus.java
  src/main/java/com/codals/greating/diet/entity/Diet.java
  src/main/java/com/codals/greating/diet/entity/Order.java
  src/main/java/com/codals/greating/diet/entity/OrderDiet.java
  src/main/java/com/codals/greating/diet/service/DietService.java
  src/main/java/com/codals/greating/diet/service/DietServiceImpl.java
  src/main/java/com/codals/greating/interceptor/LoginInterceptor.java
  src/main/java/com/codals/greating/interceptor/TemporaryUserInterceptor.java
  src/main/java/com/codals/greating/user/controller/UserRestController.java
  src/main/java/com/codals/greating/util/DateUtil.java
  src/main/resources/mappers/DailyDiet.xml
  src/main/resources/mappers/Diet.xml
  src/main/resources/mappers/Order.xml
  src/main/resources/mappers/OrderDiet.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/order/meal-choice.jsp
  src/main/webapp/WEB-INF/views/order/order-menu-info.jsp
  src/main/webapp/WEB-INF/views/order/order-result.jsp
  src/main/webapp/WEB-INF/views/order/order-step2.jsp
  src/main/webapp/resources/css/order/meal-choice.css
  src/main/webapp/resources/css/order/order-menu-info.css
  src/main/webapp/resources/js/order/meal-choice.js
  src/main/webapp/resources/js/order/order-step2.js
Labels: enhancement

#107 주문 기능 버그 수정
  src/main/java/com/codals/greating/diet/controller/DietController.java
  src/main/java/com/codals/greating/diet/dao/DailyDietDao.java
  src/main/java/com/codals/greating/diet/dao/DailyDietDaoImpl.java
  src/main/java/com/codals/greating/diet/dto/OrderDetailResponseDto.java
  src/main/java/com/codals/greating/diet/dto/OrderDietsByDateDto.java
  src/main/java/com/codals/greating/diet/dto/OrderRequestDto.java
  src/main/java/com/codals/greating/diet/dto/OrderResultResponseDto.java
  src/main/java/com/codals/greating/diet/service/DietServiceImpl.java
  src/main/resources/mappers/DailyDiet.xml
  src/main/webapp/WEB-INF/views/order/order-result.jsp
  src/main/webapp/resources/js/order/order-step2.js
Labels: bug

#111 관리자페이지 인기 식단 목록 승인
  src/main/java/com/codals/greating/admin/controller/AdminController.java
  src/main/java/com/codals/greating/admin/controller/AdminRestController.java
  src/main/java/com/codals/greating/admin/dao/AdminDao.java
  src/main/java/com/codals/greating/admin/dao/AdminDaoImpl.java
  src/main/java/com/codals/greating/admin/dto/AdminDto.java
  src/main/java/com/codals/greating/admin/service/AdminService.java
  src/main/java/com/codals/greating/admin/service/AdminServiceImpl.java
  src/main/java/com/codals/greating/mypage/controller/MyPageController.java
  src/main/resources/mappers/Admin.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/admin/admin-popularList.jsp
  src/main/webapp/resources/js/admin/admin-popular.js
Labels: enhancement

#112 관리자 식단 등록 페이지 & 등록 기능 구현
  src/main/java/com/codals/greating/admin/controller/AdminController.java
  src/main/java/com/codals/greating/admin/controller/AdminRestController.java
  src/main/java/com/codals/greating/admin/dao/AdminDao.java
  src/main/java/com/codals/greating/admin/dao/AdminDaoImpl.java
  src/main/java/com/codals/greating/admin/dto/AdminDietRegisterRequestDto.java
  src/main/java/com/codals/greating/admin/service/AdminService.java
  src/main/java/com/codals/greating/admin/service/AdminServiceImpl.java
  src/main/java/com/codals/greating/diet/entity/DailyDiet.java
  src/main/resources/mappers/Diet.xml
  src/main/webapp/WEB-INF/views/admin/admin-popularList.jsp
  src/main/webapp/WEB-INF/views/admin/admin-register.jsp
  src/main/webapp/WEB-INF/views/admin/admin-sidebar.jsp
  src/main/webapp/resources/css/admin/admin-popularList.css
  src/main/webapp/resources/css/admin/admin-register.css
  src/main/webapp/resources/css/admin/admin-sidebar.css
  src/main/webapp/resources/js/admin/admin-register.js
Labels: enhancement

#115 카카오톡 공유하기 기능 - 키값 분리
  src/main/java/com/codals/greating/diy/controller/DiyController.java
  src/main/webapp/WEB-INF/views/diy/diy-detail.jsp
  src/main/webapp/resources/js/diy/kakao-share.js
Labels: enhancement

#118 관리자 기능 1차 구현 완료
  src/main/java/com/codals/greating/admin/controller/AdminRestController.java
  src/main/java/com/codals/greating/admin/dao/AdminDao.java
  src/main/java/com/codals/greating/admin/dao/AdminDaoImpl.java
  src/main/java/com/codals/greating/admin/dto/AdminDailyDietResponseDto.java
  src/main/java/com/codals/greating/admin/service/AdminService.java
  src/main/java/com/codals/greating/admin/service/AdminServiceImpl.java
  src/main/resources/mappers/Admin.xml
  src/main/resources/mappers/Diet.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/admin/admin-register.jsp
  src/main/webapp/WEB-INF/views/admin/admin-sidebar.jsp
  src/main/webapp/resources/css/admin/admin-register.css
  src/main/webapp/resources/css/admin/admin-sidebar.css
  src/main/webapp/resources/js/admin/admin-register.js
Labels: enhancement

#119 출시예정식단 페이지 생성
  src/main/java/com/codals/greating/admin/controller/AdminController.java
  src/main/java/com/codals/greating/admin/controller/AdminRestController.java
  src/main/java/com/codals/greating/admin/dao/AdminDao.java
  src/main/java/com/codals/greating/admin/dao/AdminDaoImpl.java
  src/main/java/com/codals/greating/admin/service/AdminService.java
  src/main/java/com/codals/greating/admin/service/AdminServiceImpl.java
  src/main/resources/mappers/Admin.xml
  src/main/webapp/WEB-INF/views/admin/admin-commingsoon.jsp
  src/main/webapp/WEB-INF/views/admin/admin-sidebar.jsp
  src/main/webapp/WEB-INF/views/user/mypage-mydiy.jsp
  src/main/webapp/resources/images/food/매콤마늘종어묵볶음.png
  src/main/webapp/resources/images/food/멸치아몬드볶음.png
  src/main/webapp/resources/images/food/은이버섯무왁저지.png
Labels: enhancement

#125 프론트-백 자잘한 수정 및 연결
  src/main/java/com/codals/greating/diy/controller/DiyController.java
  src/main/java/com/codals/greating/diy/entity/Post.java
  src/main/java/com/codals/greating/diy/service/DiyServiceImpl.java
  src/main/resources/mappers/Post.xml
  src/main/webapp/WEB-INF/views/diy/diy-create.jsp
  src/main/webapp/WEB-INF/views/diy/diy-detail.jsp
  src/main/webapp/WEB-INF/views/diy/diy-main-new.jsp
  src/main/webapp/WEB-INF/views/diy/diy-main.jsp
  src/main/webapp/WEB-INF/views/diy/diy-top10.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/order/meal-choice.jsp
  src/main/webapp/WEB-INF/views/order/order-menu-info.jsp
  src/main/webapp/WEB-INF/views/order/order-step1.jsp
  src/main/webapp/WEB-INF/views/order/order-step2.jsp
  src/main/webapp/WEB-INF/views/templates/floating-adv.jsp
  src/main/webapp/WEB-INF/views/templates/floating-sharing-btn.jsp
  src/main/webapp/WEB-INF/views/templates/header.jsp
  src/main/webapp/resources/css/diy/diy-detail.css
  src/main/webapp/resources/css/diy/diy-main-new.css
  src/main/webapp/resources/css/templates/alert.css
  src/main/webapp/resources/css/templates/floating.css
  src/main/webapp/resources/css/templates/footer.css
  src/main/webapp/resources/js/diy/diy-create.js
  src/main/webapp/resources/js/diy/diy-detail.js
  src/main/webapp/resources/js/diy/diy-main.js
  src/main/webapp/resources/js/order/meal-choice.js
  src/main/webapp/resources/js/order/order-step1.js
  src/main/webapp/resources/js/templates/floating.js
  src/main/webapp/resources/js/templates/header.js
Labels: enhancement

#113 feat: 회원가입 기능(+ 유효성 검사 )
  src/main/java/com/codals/greating/user/controller/UserController.java
  src/main/java/com/codals/greating/user/controller/UserRestController.java
  src/main/java/com/codals/greating/user/dao/UserDao.java
  src/main/java/com/codals/greating/user/dao/UserDaoImpl.java
  src/main/java/com/codals/greating/user/entity/User.java
  src/main/java/com/codals/greating/user/service/UserService.java
  src/main/java/com/codals/greating/user/service/UserServiceImpl.java
  src/main/resources/mappers/User.xml
  src/main/webapp/WEB-INF/views/user/register-agreement.jsp
  src/main/webapp/WEB-INF/views/user/register-form.jsp
  src/main/webapp/resources/css/user/register-form.css
  src/main/webapp/resources/js/user/register.js
Labels: enhancement

#122 페이지네이션 오류 수정
  src/main/java/com/codals/greating/mypage/service/MyPageServiceImpl.java
  src/main/webapp/WEB-INF/views/user/mypage-mydiy.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myscrap.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myvote.jsp
Labels: enhancement

#126 주문 css 수정 및 게시물 상세 jsp 연결
  .gitignore
  src/main/webapp/WEB-INF/views/diy/diy-top10.jsp
  src/main/webapp/WEB-INF/views/order/meal-choice.jsp
  src/main/webapp/WEB-INF/views/order/order-step1.jsp
  src/main/webapp/WEB-INF/views/order/order-step2.jsp
  src/main/webapp/WEB-INF/views/user/mypage-mydiy.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myscrap.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myvote.jsp
  src/main/webapp/resources/css/order/order-result.css
  src/main/webapp/resources/css/order/order-step1.css
  src/main/webapp/resources/css/order/order-step2.css
  src/main/webapp/resources/js/diy/diy-top10.js
  src/main/webapp/resources/js/order/order-step1.js
  src/main/webapp/resources/js/order/order-step2.js
  src/main/webapp/resources/js/user/mypage-mydiy.js
  src/main/webapp/resources/js/user/mypage-myscrap.js
  src/main/webapp/resources/js/user/mypage-myvote.js
Labels: enhancement

#130 관리자 페이지 js파일 수정
  src/main/java/com/codals/greating/admin/controller/AdminRestController.java
  src/main/java/com/codals/greating/admin/dao/AdminDao.java
  src/main/java/com/codals/greating/admin/dao/AdminDaoImpl.java
  src/main/java/com/codals/greating/admin/service/AdminService.java
  src/main/java/com/codals/greating/admin/service/AdminServiceImpl.java
  src/main/resources/mappers/Admin.xml
  src/main/webapp/WEB-INF/views/admin/admin-popularList.jsp
  src/main/webapp/WEB-INF/views/admin/admin-sidebar.jsp
  src/main/webapp/resources/css/admin/admin-popularList.css
  src/main/webapp/resources/js/admin/admin-popular2.js
Labels: bug

#132 각종 예외 처리 및 리팩토링
  src/main/java/com/codals/greating/constant/SessionKey.java
  src/main/java/com/codals/greating/diet/controller/DietController.java
  src/main/java/com/codals/greating/diet/controller/DietRestController.java
  src/main/java/com/codals/greating/diet/dao/DailyDietDao.java
  src/main/java/com/codals/greating/diet/dao/DailyDietDaoImpl.java
  src/main/java/com/codals/greating/diet/service/DietServiceImpl.java
  src/main/java/com/codals/greating/diy/controller/DiyController.java
  src/main/java/com/codals/greating/diy/dao/DiyDAO.java
  src/main/java/com/codals/greating/diy/dao/DiyDAOImpl.java
  src/main/java/com/codals/greating/exception/ErrorCode.java
  src/main/java/com/codals/greating/user/controller/UserController.java
  src/main/java/com/codals/greating/user/controller/UserRestController.java
  src/main/java/com/codals/greating/user/dao/UserDao.java
  src/main/java/com/codals/greating/user/dao/UserDaoImpl.java
  src/main/java/com/codals/greating/user/entity/Role.java
  src/main/java/com/codals/greating/user/entity/User.java
  src/main/java/com/codals/greating/user/exception/AlreadyLoggedInException.java
  src/main/java/com/codals/greating/user/service/UserServiceImpl.java
  src/main/webapp/WEB-INF/views/diy/diy-create.jsp
  src/main/webapp/WEB-INF/views/order/meal-choice.jsp
  src/main/webapp/WEB-INF/views/order/order-result.jsp
  src/main/webapp/WEB-INF/views/templates/header.jsp
  src/main/webapp/WEB-INF/views/user/register-agreement.jsp
  src/main/webapp/WEB-INF/views/user/register-form.jsp
  src/main/webapp/resources/js/order/meal-choice.js
  src/main/webapp/resources/js/templates/header.js
  src/test/java/com/codals/greating/user/service/UserServiceImplTest.java
Labels: refactor

#141 2주치 식단 등록시 캐싱 + 조회시 캐시에서 가져오기
  pom.xml
  src/main/java/com/codals/greating/admin/service/AdminServiceImpl.java
  src/main/java/com/codals/greating/config/RedisConfig.java
  src/main/java/com/codals/greating/diet/entity/DailyDiet.java
  src/main/java/com/codals/greating/diy/service/DiyServiceImpl.java
  src/main/resources/mappers/DailyDiet.xml
  src/main/webapp/WEB-INF/views/admin/admin-register.jsp
Labels: enhancement

#136 post status 변경 스케줄러 적용
  src/main/java/com/codals/greating/HomeController.java
  src/main/java/com/codals/greating/diy/dao/DiyDAO.java
  src/main/java/com/codals/greating/diy/dao/DiyDAOImpl.java
  src/main/java/com/codals/greating/diy/service/DiyService.java
  src/main/java/com/codals/greating/diy/service/DiyServiceImpl.java
  src/main/resources/mappers/Post.xml
  src/main/webapp/WEB-INF/spring/datasource-context.xml
Labels: enhancement

#144 TOP 10 도시락 Redis 캐싱
  src/main/java/com/codals/greating/diy/service/DiyServiceImpl.java
Labels: enhancement

#137 [Front] DIY 검색 - 페이지네이션 구현 완료
  src/main/java/com/codals/greating/diy/controller/DiyController.java
  src/main/java/com/codals/greating/diy/controller/DiyRestController.java
  src/main/java/com/codals/greating/diy/dao/DiyDAO.java
  src/main/java/com/codals/greating/diy/dao/DiyDAOImpl.java
  src/main/java/com/codals/greating/diy/dto/SearchRequestDto.java
  src/main/java/com/codals/greating/diy/dto/SearchResponseDto.java
  src/main/java/com/codals/greating/diy/service/DiyService.java
  src/main/java/com/codals/greating/diy/service/DiyServiceImpl.java
  src/main/java/com/codals/greating/mypage/dao/MyPageDaoImpl.java
  src/main/java/com/codals/greating/mypage/service/MyPageService.java
  src/main/java/com/codals/greating/util/pagination/Pagination.java
  src/main/resources/mappers/Post.xml
  src/main/webapp/WEB-INF/views/diy/diy-main-new.jsp
  src/main/webapp/WEB-INF/views/templates/pagination.jsp
  src/main/webapp/resources/css/templates/pagination.css
  src/main/webapp/resources/js/diy/diy-main.js
  src/main/webapp/resources/js/templates/pagination.js
Labels: enhancement

#138 마이페이지 삭제 기능 구현 및 스크랩, 투표식단 링크, 제목 추가
  src/main/java/com/codals/greating/mypage/controller/MyPageController.java
  src/main/java/com/codals/greating/mypage/dao/MyPageDao.java
  src/main/java/com/codals/greating/mypage/dao/MyPageDaoImpl.java
  src/main/java/com/codals/greating/mypage/dto/MyPageScrapDto.java
  src/main/java/com/codals/greating/mypage/service/MyPageService.java
  src/main/java/com/codals/greating/mypage/service/MyPageServiceImpl.java
  src/main/resources/mappers/MyPage.xml
  src/main/webapp/WEB-INF/views/user/mypage-mydiy.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myscrap.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myvote.jsp
  src/main/webapp/WEB-INF/views/user/mypage-sidebar.jsp
  src/main/webapp/resources/css/user/mypage-mydiy.css
  src/main/webapp/resources/images/user/mypage-main.png
  src/main/webapp/resources/js/user/mypage-mydiy.js
Labels: enhancement

#150 [Back] 캐싱 - 마이그리팅 Preview 캐싱
  pom.xml
  src/main/java/com/codals/greating/admin/service/AdminService.java
  src/main/java/com/codals/greating/admin/service/AdminServiceImpl.java
  src/main/java/com/codals/greating/config/RedisConfig.java
  src/main/java/com/codals/greating/constant/CacheKey.java
  src/main/java/com/codals/greating/diet/dto/PreviewDietResponseDto.java
  src/main/java/com/codals/greating/diet/dto/PreviewResponseDto.java
  src/main/java/com/codals/greating/diet/entity/DailyDiet.java
  src/main/java/com/codals/greating/diet/entity/Diet.java
  src/main/java/com/codals/greating/diet/service/DietServiceImpl.java
  src/main/webapp/WEB-INF/views/order/order-menu-info.jsp
Labels: enhancement

#159 Redis 관련 오류 해결
  src/main/java/com/codals/greating/config/RedisGenericJacksonConfig.java
  src/main/java/com/codals/greating/config/RedisJacksonConfig.java
  src/main/java/com/codals/greating/constant/CacheKey.java
  src/main/java/com/codals/greating/diet/dto/PreviewResponseDto.java
  src/main/java/com/codals/greating/diet/service/DietServiceImpl.java
  src/main/java/com/codals/greating/diy/dao/DiyDAOImpl.java
  src/main/java/com/codals/greating/diy/service/DiyServiceImpl.java
Labels: bug, enhancement

#152 이벤트 기반 주문 확정 메일 발송 구현
  pom.xml
  src/main/java/com/codals/greating/config/AsyncConfig.java
  src/main/java/com/codals/greating/config/ThymeleafConfig.java
  src/main/java/com/codals/greating/diet/OrderConfirmationEvent.java
  src/main/java/com/codals/greating/diet/OrderConfirmationHandler.java
  src/main/java/com/codals/greating/diet/controller/DietRestController.java
  src/main/java/com/codals/greating/diet/dto/OrderDietRequestDto.java
  src/main/java/com/codals/greating/diet/service/DietServiceImpl.java
  src/main/java/com/codals/greating/email/config/MailConfig.java
  src/main/java/com/codals/greating/email/dto/OrderDietInfoDto.java
  src/main/java/com/codals/greating/email/dto/OrderDto.java
  src/main/java/com/codals/greating/email/service/EmailService.java
  src/main/java/com/codals/greating/email/service/EmailServiceImpl.java
  src/main/java/com/codals/greating/external/sender/EmailSender.java
  src/main/java/com/codals/greating/external/sender/GmailEmailSender.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/spring/root-context.xml
  src/main/webapp/WEB-INF/views/email/order-confirmation.html
  src/main/webapp/resources/js/order/meal-choice.js
Labels: enhancement

#160 머지하면서 생긴 버그 해결
  src/main/java/com/codals/greating/diet/service/DietServiceImpl.java
Labels: bug

#173 인터셉터 재설정 및 불필요한 메서드 제거
  src/main/java/com/codals/greating/admin/controller/AdminRestController.java
  src/main/java/com/codals/greating/diet/controller/DietController.java
  src/main/java/com/codals/greating/diet/controller/DietRestController.java
  src/main/java/com/codals/greating/diy/controller/DiyRestController.java
  src/main/java/com/codals/greating/user/controller/UserRestController.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
Labels: enhancement

#176 관리자 전체보기 페이지 추가
  src/main/java/com/codals/greating/admin/controller/AdminController.java
  src/main/java/com/codals/greating/admin/controller/AdminRestController.java
  src/main/java/com/codals/greating/admin/dao/AdminDao.java
  src/main/java/com/codals/greating/admin/dao/AdminDaoImpl.java
  src/main/java/com/codals/greating/admin/service/AdminService.java
  src/main/java/com/codals/greating/admin/service/AdminServiceImpl.java
  src/main/resources/mappers/Admin.xml
  src/main/webapp/WEB-INF/views/admin/admin-allList.jsp
  src/main/webapp/WEB-INF/views/admin/admin-commingsoon.jsp
  src/main/webapp/WEB-INF/views/admin/admin-sidebar.jsp
  src/main/webapp/WEB-INF/views/templates/header.jsp
  src/main/webapp/resources/js/admin/admin-commingSoon.js
  src/main/webapp/resources/js/admin/admin-popular2.js
Labels: enhancement

#178 마이페이지 메인페이지 생성 및 링크 수정
  src/main/java/com/codals/greating/mypage/controller/MyPageController.java
  src/main/java/com/codals/greating/mypage/dto/MyPageScrapDto.java
  src/main/webapp/WEB-INF/views/templates/header.jsp
  src/main/webapp/WEB-INF/views/user/mypage-main.jsp
  src/main/webapp/WEB-INF/views/user/mypage-mydiy.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myscrap.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myvote.jsp
  src/main/webapp/resources/css/user/mypage-main.css
  src/main/webapp/resources/css/user/mypage-mydiy.css
  src/main/webapp/resources/js/user/mypage-myscrap.js
  src/main/webapp/resources/js/user/mypage-myvote.js
Labels: enhancement

#182 마이페이지 결제완료 주문 수 조회
  src/main/java/com/codals/greating/admin/controller/AdminRestController.java
  src/main/java/com/codals/greating/constant/SessionKey.java
  src/main/java/com/codals/greating/diet/dao/OrderDao.java
  src/main/java/com/codals/greating/diet/dao/OrderDaoImpl.java
  src/main/java/com/codals/greating/diet/service/OrderService.java
  src/main/java/com/codals/greating/diet/service/OrderServiceImpl.java
  src/main/java/com/codals/greating/mypage/controller/MyPageController.java
  src/main/resources/mappers/Order.xml
  src/main/webapp/WEB-INF/views/templates/header.jsp
  src/main/webapp/WEB-INF/views/user/mypage-welcome.jsp
Labels: enhancement

#183 admin, mypage css수정
  src/main/resources/mappers/Admin.xml
  src/main/webapp/WEB-INF/views/admin/admin-allList.jsp
  src/main/webapp/WEB-INF/views/admin/admin-popularList.jsp
  src/main/webapp/WEB-INF/views/admin/admin-sidebar.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myscrap.jsp
  src/main/webapp/WEB-INF/views/user/mypage-myvote.jsp
  src/main/webapp/resources/css/admin/admin-sidebar.css
  src/main/webapp/resources/css/user/mypage-sidebar.css
  src/main/webapp/resources/js/templates/header.js
Labels: enhancement

#184 자잘한 수정
  src/main/java/com/codals/greating/admin/service/AdminServiceImpl.java
  src/main/java/com/codals/greating/interceptor/LoginInterceptor.java
  src/main/webapp/WEB-INF/views/diy/diy-main-new.jsp
  src/main/webapp/WEB-INF/views/templates/floating-sharing-btn.jsp
  src/main/webapp/WEB-INF/views/templates/header.jsp
  src/main/webapp/WEB-INF/views/user/login.jsp
  src/main/webapp/resources/css/templates/pagination.css
  src/main/webapp/resources/css/user/mypage-main.css
  src/main/webapp/resources/images/diy/youtube-new.png
  src/main/webapp/resources/images/diy/youtube.png
  src/main/webapp/resources/js/diy/diy-main.js
  src/main/webapp/resources/js/templates/header.js
  src/main/webapp/resources/js/templates/pagination.js
Labels: enhancement

#190 누락 이미지 파일 추가
  src/main/webapp/resources/images/food/오리깻잎불고기.png
Labels: documentation

#191 식단 설계 및 주문과정 버그 해결
  src/main/java/com/codals/greating/diet/dto/OrderDetailResponseDto.java
  src/main/webapp/WEB-INF/views/order/order-result.jsp
  src/main/webapp/resources/js/order/meal-choice.js
  src/main/webapp/resources/js/order/order-step1.js
  src/main/webapp/resources/js/order/order-step2.js
Labels: bug
